### ISSUE TITLE
Implement pen

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#25]
It should work using an underlying canvas: Basically it would be single canvas spanning the whole page that would get drawn on by each sprite that has a pen down whenever a move function is called.

**Comment by davidnagli** [comment]
### Interface should look like this:

``` javascript
mySprite.pen.down()
mySprite.pen.up()
mySprite.pen.color = color
mySprite.pen.opacity = opacity
mySprite.pen.size = size

mouse.pen.down()
mouse.pen.up()
mouse.pen.color = color
mouse.pen.opacity = opacity
mouse.pen.size = size

pen.clear() // clears all pen marks made by all sprites
```

**Comment by skistaddy** [comment]
Might want to look at this. Not sure if it would work, I just googled it. http://stackoverflow.com/questions/4270485/drawing-lines-on-html-page
