### ISSUE TITLE
Running?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#28]
How do we run the file once we create it?

**Comment by davidnagli** [comment]
I covered this in the docs:
https://docs.google.com/document/d/1zh6w54efiQVnsy3F5DeVzOfAJO8UNi0CaRKeYGWocNg

**Comment by davidnagli** [comment]
What OS are you using for development?

**Comment by davidnagli** [comment]
If it's Mac or Linux the method described in the docs should work

**Comment by skistaddy** [comment]
Mac

**Comment by davidnagli** [comment]
Yep, it's in the docs

**Comment by skistaddy** [comment]
K
