### ISSUE TITLE
Glide () seconds to (x), (y)

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#29]
We need to implement this.

**Comment by davidnagli** [comment]
How is this different from the mySprite.glideTo() that we already have implemented?

**Comment by skistaddy** [comment]
This glides to the coordinates over a set amount of time. So it would take _blank_ amount of seconds to get there.

**Comment by davidnagli** [comment]
That's exactly how glideTo() works right now:

mySprite.glideTo(x, y, time)

mySprite.glideTo(otherSprite, time)

**Comment by skistaddy** [comment]
Oh, well that isn't included in the docs.

**Comment by davidnagli** [comment]
Oh, thanks for letting me know. I'll add it to the docs as soon as
possible.

**Comment by skistaddy** [comment]
K.
