### ISSUE TITLE
Styling HTML in Sprites.

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#30]
Plain HTML isn't going to look good, so are we going to have the user write in all their CSS using CSS attributes and style tags?

**Comment by skistaddy** [comment]
Would CSS refs still work?

**Comment by davidnagli** [comment]
Yep, the user would add CSS just like they would in any other HTML: Style
tags in their HTML file (or using Link HREF for external style sheets)

**Comment by skistaddy** [comment]
Ok.
