### ISSUE TITLE
Add Feature: pickRandom()

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#31]
```javascript
pickRandom(min, max)  
//returns a random number (randomNumber >= min && randomNumber <= max)
```

**Comment by skistaddy** [comment]
Added in https://github.com/Scratch-JS/Scratch-JS/commit/6e99defe171081568711d62dfb40e97c4d31bdb0

**Comment by davidnagli** [comment]
I had to revert this commit, please recommit a readable and tested version

**Comment by skistaddy** [comment]
K

**Comment by skistaddy** [comment]
Fixed by https://github.com/Scratch-JS/Scratch-JS/commit/fbad98c53250700b007d3faa44a12e731462596e
