### ISSUE TITLE
Add Feature: mySprite.goToFront()

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#35]
Alright, I did a bit of research, and found that the following would work.
```javascript
      this.goToFront = function () {
         this.element.style.zIndex = front;
         front++;
         this.element.style.position = "relative";
     }
```
We will need to create a global variable called `front`.

**Comment by skistaddy** [comment]
There is a small problem though, any element that's z index is changed without the above function will not affect the front variable, which means the sprite in "front" could actually be behind something, depending on the value of `front`.

**Comment by skistaddy** [comment]
So we need to sense when other elements' z index is changed.

**Comment by davidnagli** [comment]
z-index is certainly an option, however, I think it's gonna be allot more practical to physically reorder the DOM elements themselves.

For example, if we had two sprites, instead of just changing their z-index, we could actually change their order in the HTML

We can do this using `.insertBefore()`

**Comment by skistaddy** [comment]
Ok, so which way is which? Does insert before bring it to the front or back?

**Comment by davidnagli** [comment]
It gives us the control... if the parameter is set to null it can be used
to go to the front, but it can also be used to go forward, backward and to
the back.

**Comment by davidnagli** [comment]
It allows us to insert the Sprite before any element in the DOM, or as the
last element. Read the MDN documentation for more.

**Comment by skistaddy** [comment]
K.

**Comment by skistaddy** [comment]
So would we need to sense which DOM element is in the front and insert it there? Or could we simply to 
```javascript
.insertBefore(whatever, document)
```

**Comment by davidnagli** [comment]
For goToFront() we can leave the second parameter as null, and it'll go to
the front automatically.

For goFoward() we would also use insertBefore(), but we would need to
"sense" the element in front of it.

Please take a look at the MDN documentation:
https://developer.mozilla.org/en-US/docs/Web/API/Node/insertBefore

**Comment by skistaddy** [comment]
Ok, I get it.

**Comment by skistaddy** [comment]
So for the first parameter on goToFront(), should I set it to `this`? Like so:
```
     this.goToFront = function () {
         this.insertBefore(this);
     };
```

**Comment by davidnagli** [comment]
No, `this` is gonna be a reference to the Sprite object. `this.element` contains the HTML element corresponding to the sprite

**Comment by skistaddy** [comment]
K thanks.

**Comment by skistaddy** [comment]
Alright, I should have `goToFront()` solved.

**Comment by skistaddy** [comment]
Solved in https://github.com/Scratch-JS/Scratch-JS/commit/18403045b94fe873a6974c8dc4b2c4fa3599b0c4

**Comment by davidnagli** [comment]
This needs to be tested and re-commited

**Comment by skistaddy** [comment]
K.

**Comment by davidnagli** [comment]
Doing this one too 😆
