### ISSUE TITLE
Add Feature: mySprite.goBackward()

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#36]
```javascript
mySprite.goBackward(layers)
```

**Comment by skistaddy** [comment]
I added the layers parameter, just so you know.

**Comment by davidnagli** [comment]
Do you wanna work on the layer features?

**Comment by davidnagli** [comment]
Assign them to yourself if you are, also please put them into the "in progress" in the [Project board ](https://github.com/Scratch-JS/Scratch-JS/projects/2#card-1950262)

**Comment by skistaddy** [comment]
K.
