### ISSUE TITLE
Add feature: pen.clear()

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#38]
```javascript
pen.clear()
//no parameters, shouldn't return anything
```

**Comment by skistaddy** [comment]
http://stackoverflow.com/questions/2142535/how-to-clear-the-canvas-for-redrawing

**Comment by skistaddy** [comment]
This should work, I'll look into it closer.

**Comment by skistaddy** [comment]
Quick question: 
Do we want to make it a sprite function or global function?
```
mySprite.clear()
clear()
```

**Comment by davidnagli** [comment]
That link should work.

It should be a sprite function

**Comment by skistaddy** [comment]
So do you want mySprite.clear() or something else?

**Comment by davidnagli** [comment]
`mySprite.clearPen()`

**Comment by skistaddy** [comment]
K.

**Comment by davidnagli** [comment]
Wait, I think I never committed the working pen code...

**Comment by davidnagli** [comment]
If you don't mind, I'm gonna do this one... I ran out of (simple) things to do.

**Comment by skistaddy** [comment]
No problem. :)
