### ISSUE TITLE
Add feature: Keypress events

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#39]
```javascript
whenKeyPressed(keyValue)
//returns a Promise that should get resolved whenever that key is pressed

/*Example Usage*/
whenKeyPressed("a").then({
    //do something
})
```

**Comment by skistaddy** [comment]
I've already worked on this. Should be easy for me to do.

**Comment by skistaddy** [comment]
Quick question, are we going to wait until the key is pressed and then execute the code, or are we going to skip over it and wait for it like an event?

**Comment by davidnagli** [comment]
Not really sure what you mean, but it should be using an event listener.

**Comment by bjskistad** [comment]
Nvm, gtg, ttyl

**Comment by davidnagli** [comment]
I ran out of things to do, I'm gonna do this one since you don't seem to be doing it

**Comment by davidnagli** [comment]
Promises could only be resolved once, so I'm gonna implement it differently.

```javascript
whenKeyPressed {
    //do something
    //anything here can access an object called event
    //for example:
    say(event.key)
}
```
