### ISSUE TITLE
Add Feature: Sprite cloning

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#41]
```javascript
mySprite.clone()
//returns the cloned sprite's Sprite object
```

Clone should work by copying `mySprite` into a new variable, then setting its `.element` property to a DOM element clone of `mySprite.element`

**Comment by skistaddy** [comment]
Seems simple enough. What should the clone be called? Should that be a parameter in the function? Something like
```javascript
mySprite.clone("myNewSprite") // Copies sprite and names it "myNewSprite"
```

**Comment by skistaddy** [comment]
And if the parameter isn't filled, it will set the name to `mySprite1` or something.

**Comment by davidnagli** [comment]
What do you mean by "what should it be called"? Sprites don't really have names, they just have _optional_ variables

Technically, the following works perfectly fine:

```javascript
whenPageLoads {
    new Sprite(0, 0, "spriteImage.png")
}
```

**Comment by skistaddy** [comment]
ok
