### ISSUE TITLE
Positioning for HTML sprites not working

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#42]
```javascript
//this:
new Sprite(20, 30, "<button>hi</button>")
//does the same thing as this:
new Sprite(0, 0, "<button>hi</button>")
```

Just add absolute positioning to the elements and give them positions

**Comment by skistaddy** [comment]
http://stackoverflow.com/questions/28598910/position-an-html-element-at-any-x-y-coordinate-in-a-page
