### ISSUE TITLE
Should we change Sprite constructor argument’s order?

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#43]
I'm not sure what I was thinking when I decided to make the order of the arguments the way they are:
```javascript
new Sprite(x, y, value, scaleFactor)
```
I think we change it to:
```javascript
new Sprite(value, x, y, scaleFactor)
```
For example:
```javascript
//before
mySprite = new Sprite(20, 50, "spriteImage.png", 0.4)

//after
mySprite = new Sprite("spriteImage.png", 20, 50, 0.4)
```

It's an easy switch, but I just wanted to get approval since I know that it'll break any existing SJS code, and the documentation will need to be updated.

**Comment by skistaddy** [comment]
I think that the original is actually better.

You see, for the original, they actually **_need_** to position and align the sprite, as the first arguments come before the values. 

The way you're suggesting it, we could have sprites with no alignment on the document, which wouldn't be good at all.

**Comment by davidnagli** [comment]
Just because it's not first, doesn't mean we have to make it optional.

Anyways, we can just make the default position x: 0 y:0 (the center of
the page).

I think the switch is important because even though I designed and wrote
the constructor function myself, I still find myself accidentally misusing
the parameters during testing.

If you really think it's necessary to *not* change it we don't have to, but
I really think it's pretty counter intuitive the way it is now.

**Comment by skistaddy** [comment]
Ok, you're the boss.

**Comment by skistaddy** [comment]
I support it if you do.

**Comment by davidnagli** [comment]
haha k

**Comment by skistaddy** [comment]
So, what was the final decision?
