### ISSUE TITLE
Better commit messages, readable and tested code, and issue closing!

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#44]
@bjskistad I have a few questions/ comments:

- Please use better commit messages than "updated index.js"
- Please write more readable code (the variable names don't make any sense in the pickRandom feature)
- Also, I just wanted to make sure that you're testing out the features you add before you commit them.

Last, I wanted to give you a heads up that you can save allot of time by [closing the issues in the commit message](https://help.github.com/articles/closing-issues-via-commit-messages/) 

Totally optional, but a cool life hack ^

**Comment by skistaddy** [comment]
Will do.

**Comment by skistaddy** [comment]
My testing environment is a bit limited as of now, but I will make sure I get around to testing all my features.

**Comment by davidnagli** [comment]
Please test before you commit to the master branch.

If you wanna check in unstable features, do it on a different branch and merge them when you test them.

**Comment by davidnagli** [comment]
I'm gonna revert all your changes for now, if that's fine with you...

**Comment by skistaddy** [comment]
Ok...

**Comment by skistaddy** [comment]
I'll test rn, just let me set up an environment quick.
