### ISSUE TITLE
File type? Running?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#45]
Is Scratch-JS going to be run in a JavaScript file, an HTML file, or it's own file? How do we run it? 
I just created the following HTML file and it didn't even create the sprites:
```html
<html>
    <script src="/index.js">
        var mySprite = new Sprite(50, 50, "<h1>hi</h1>", 0);
        var behind   = new Sprite(50, 50, "<h1>hello there</h1>", 0);
        mySprite.goToFront();
    </script>
</html>
```

**Comment by davidnagli** [comment]
Please refer to the docs! I'm pretty sure I explained it there.

**Comment by skistaddy** [comment]
I'm going to start doing some of the docs on the website.

**Comment by davidnagli** [comment]
K. I'll work on #45

**Comment by skistaddy** [comment]
M'kay, gl.
