### ISSUE TITLE
Moving isn't working.

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#46]
Several of the example scripts don't move the sprite at all. Needs to be fixed.

**Comment by skistaddy** [comment]
And what happened to like all the labels.

**Comment by davidnagli** [comment]
For example???

**Comment by skistaddy** [comment]
```
whenPageLoads {
    mySprite = new Sprite(0, 0, "<h1>Lol.</h1>");
    mySprite.turn(45)
    mySprite.move(100)
    wait(1000).then({
       mySprite.goTo(100,0); 
    })
}
```
Turns the sprite but doesn't move it.

**Comment by davidnagli** [comment]
I already have an issue open for this... HTML Sprite positioning broke.
Please use image sprites for now.

**Comment by davidnagli** [comment]
Please see #42

**Comment by skistaddy** [comment]
ok
