### ISSUE TITLE
How do I control a clone?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#50]
How exactly do I control a clone? Is there a callback or something?

**Comment by skistaddy** [comment]
I'm also wondering how I would delete a clone once I'm done with it?

**Comment by davidnagli** [comment]
`mySprite.clone()` returns the clone which you can use and control just like any other sprite:
```javascript
mySprite = new Sprite(...)
myClone = mySprite.clone()
myClone.move(50)
```

As for deleting clones, I added the feature for cloning Sprites earlier today (for unrelated reasons). The delete functionality should work on clones too:

```javascript
myClone.delete()

//works in the same way any sprite
someSprite.delete()
```

**Comment by skistaddy** [comment]
K, thanks.
