### ISSUE TITLE
Mutliple processes?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#51]
Can we have multiple processes going on in the same file? Maybe triggered by events?

**Comment by skistaddy** [comment]
Maybe you can have multiple `whenPageLoads` too?

**Comment by davidnagli** [comment]
JavaScript in browsers doesn't really have processes, but it does still have a async events that allow it to behave like a multi process program (using the event loop)

Scratch-JS does have events: when page loads, when key pressed, when clicked, etc. 

However I don't see any beinfits or reasons why you would want multiple whenPageLoads handlers.

**Comment by skistaddy** [comment]
The forever loop in toilet-paper-rolls has a wait in it, this either delays clone creation or delays the clone's job. I need to have two whenPageLoads similar to two When Green Flagged Clickeds.

**Comment by davidnagli** [comment]
Forever can take an optional delay parameter.

**Comment by skistaddy** [comment]
It isn't the forever causing the delay, it's a wait inside of the loop.

**Comment by davidnagli** [comment]
What I'm trying to say is that wait loops don't work properly inside forever loops (there are some valid reasons). Because of this it's recommended to use a special "delay" parameter that you can add to the forever loop instead using the wait():


```javascript
//DON'T DO THIS
forever({
    wait(20).then({
        //something
    })
})

//DO THIS:
forever({
     //something
}, 20)
```

In most cases using the "delay" parameter instead of the wait inside should fix any issues you have.

**Comment by davidnagli** [comment]
Try eliminating the wait loop from the forever, then let me know if the bug persists.

If it does, try to explain in more detail exactly what you want to achieve and paste the relevant code.
