### ISSUE TITLE
Notice: I'm going to be changing the syntax/ implementation of the say() and ask() functions

### ISSUE THREAD

**Issue by davidnagli** [davidnagli/Scratch-JS#52]
Previously, say() and ask() would just open JavaScript popup alerts and prompts. I'm now changing it to a more Scratch-like implementation with speech bubbles.

I will commit the code shortly, but I wanted to let everybody know that existing code that uses say() or ask() may break or be otherwise affected by the change when it get's updated.

**The new ask() implementation looks like this:**

```javascript
//Syntax
mySprite.ask(question).then({
     //do stuff when you get an answer
})

//Example:
mySprite.ask("Some question goes here").then({
    say(this.answer) //this.answer contains the inputted text
})
```
![screen shot 2017-03-17 at 9 16 13 am](https://cloud.githubusercontent.com/assets/6759650/24044649/917c7f28-0af2-11e7-8eb9-1d1132d526ad.png)

**Then new say() implementation looks like this:** 
```javascript
//Syntax:
mySprite.say(text, time).then({
    //do something after speech bubble disappears
})

//Example: Say "Hello this is text" for 1000 milliseconds (1 second)
mySprite.say("Hello, this is text", 1000).then({
    //this will get executed after 1000 milliseconds (1 second) when the speech bubble disappears)
    ...
})
```

**Comment by davidnagli** [comment]
![screen shot 2017-03-17 at 10 12 25 am](https://cloud.githubusercontent.com/assets/6759650/24046821/3e57cc78-0afa-11e7-94b7-a9dbe8dcec06.png)

**Comment by skistaddy** [comment]
K
