### ISSUE TITLE
Semi-colons?

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#54]
If you look at the README code examples, the semi-colon usage or not is pretty shifty.

Is Scratch.js using semi-colons or not?

**Comment by davidnagli** [comment]
Scratch-JS has the same semi colons as JavaScript, in that they are pretty much optional. 

I agree that the README example needs to be cleaned up a bit to prevent beginners from getting confused. 

I personally just add semicolons where ever my IDE tells me to....

**Comment by skistaddy** [comment]
K.
