### ISSUE TITLE
Sprite objects

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#55]
If you need to say a direction of a sprite in Scratch, you would do.
```
say[(direction)]
```
I was thinking that in SJS we could do
```
sprite = //blah blah blah sprite stuff;
alert(sprite.direction);
```
Would this work?

**Comment by skistaddy** [comment]
Or is there some JS workaround for this.

**Comment by skistaddy** [comment]
(btw i didn't see this in the docs)

**Comment by davidnagli** [comment]
Do you mind providing a more concrete example of your first statement `say[(direction)]`?

I’m not sure if the `[]` represent an array or something… you **don't** have to bother writing the sprite initialization stuff… I’m just not understanding what you mean 100%

**Comment by skistaddy** [comment]
Sorry, that is a representation of the scratch editor blocks.

**Comment by davidnagli** [comment]
Oh I see, so the first code snippet was the Scratch code and the second code snippet is your proposed Scratch-JS syntax….

In that case, you’ve got it! This is exactly how it **already** works. Every sprite is an object that contains a direction property amongst other things.

I totally forgot to put it in the docs, sorry.

Please let me know if I misunderstood you.

```
whenPageLoads {
    // Create a new sprite at position (0,0)
    mySprite = new Sprite(0, 0, “sprite.jpg”);

    //Say the direction
    say(mySprite.direction)
    
    //Or, like in your example, you can use the native alert function (say and alert do exactly the same thing)
    alert(mySprite.direction)
}
```

**Comment by skistaddy** [comment]
Awesome! Exactly what I was looking for. Thanks!

**Comment by davidnagli** [comment]
In case you need it, the static properties of the Sprite object are:

* x - the x position of the sprite (with origin on the center of the screen)
* y - the y position
* direction - a number representing the angle the sprite is turned counterclockwise
* isHidden - (boolean) whether or not the sprite is currently hidden using .hide() or .show()
* penIsDown - (boolean) whether or not the **sprite’s pen** is down 
* element - the underlying HTML element of the sprite
* speechBuble - the underlying HTML element of the speech bubble used for say()
* loaded - (boolean) pretty much only used internally, but represents weather the sprites img (if it is an image) has finished loading

**Comment by skistaddy** [comment]
Thanks, I was just about to ask how to get the x position. :)

**Comment by davidnagli** [comment]
Also, I would like to correct this comment:
```
//Or, like in your example, you can use the native alert function (say and alert do exactly the same thing)
```

I totally forgot that I implemented a speech bubble system for Scratch-JS, so `say()` no longer uses the native `alert()` function and instead creates a speech bubble for the sprite! And `say()` is no longer a global function, it’s now a method of the sprite:

```

mySprite.say(“Hey bro!”)

```

**Comment by skistaddy** [comment]
Awesome!
