### ISSUE TITLE
Stage properties

### ISSUE THREAD

**Issue by skistaddy** [davidnagli/Scratch-JS#56]
I don't know if this exists or not, but could we possibly implement a stage object that has the following properties?
```
right: (The right side of the page in pixels, ex: 240),
left: (The left side of the page in pixels, ex: -240)
```

**Comment by skistaddy** [comment]
So this could be utilized
```
say(stage.right);
```
As a native variable, like `Math`.

**Comment by davidnagli** [comment]
Can you elaborate on what you mean by “left/right side of the page”

**Comment by skistaddy** [comment]
Like the project stage, is the best way I can put it.

**Comment by skistaddy** [comment]
![screen shot 2017-08-30 at 6 02 19 pm](https://user-images.githubusercontent.com/16439579/29898800-6e77ee3e-8dad-11e7-9dbc-b69e77cb69fc.png)

**Comment by skistaddy** [comment]
`stage.right` would be 240 in this example, sorta like `window.width` some how?

**Comment by davidnagli** [comment]
Ohh ya! Scratch-JS has an object called `page`.

It has some kind confusingly named properties, so I’ll explain:

```
page.originOffsetX // how far from the left side of the screen the “stage origin is” which is just where all x, y coordinates originate from…. it’s located in the center of the page

page.originOffsetY // same as above just the distance from the top of the page

page.maxX //probably what you’re looking for - the maximum `x` value on the screen (aka widthOfStage / 2)

page.maxY // maximum possible y value….
```

**Comment by davidnagli** [comment]
Note that **all** of those properties react properly when the window is resized!

**Comment by davidnagli** [comment]
Fundamentally though, `page.maxX` and `page.maxY`are exactly what you’re looking for. They show the maximum x & y position of the stage, which is what Scratch shows when you hover your mouse to a corner/edge and read those numbers on the bottom of the stage.

**Comment by skistaddy** [comment]
Awesome! Thanks!

**Comment by davidnagli** [comment]
Np!
